### PR TITLE
Added image folder, images and changed some css to make the website look better

### PR DESCRIPTION
**Pull request by barkhayadav12**

### CODE REVIEW

**Comment by Divyansh-Singhal** [comment]
Images are not loading please check that. For this I cannot merge for now. Fix this and I will do it. Also confirm you have added the volume slider?

**Comment by Divyansh-Singhal** [comment]
Rectify the conflicts with the branch and we will merge.

**Comment by barkhayadav12** [comment]
How do I resolve the conflict? Can you please guide me on that? Should I remove all those codes where the red line is appearing?

**Comment by Divyansh-Singhal** [comment]
Pull the changes first and then push them again. Go to source control in vscode and sync the changes. It will automatically do the necessary actions else do it manually.

**Comment by barkhayadav12** [comment]
Done. Please check @Divyansh-Singhal

**Comment by Divyansh-Singhal** [comment]
[https://musicano-qamu6vdbs-techno-developers-team.vercel.app/](url)

See this and you  will find why i cannot merge.

**Comment by barkhayadav12** [comment]
Then what do I do now?  I am new to open source, I don't  know why that's happening. What do I do now?

**Comment by Divyansh-Singhal** [comment]
Do one thing. Pull the code again in a new folder. Now make your changes in the new one just copy paste the old one and then make pull request. And before pull request do check on the localhost.

**Comment by barkhayadav12** [comment]
Done. please check This is how it looks 
Screenshot 2023-10-04 113916
This is how it looks on the localhost.

**Comment by Divyansh-Singhal** [comment]
Looks good. 

Hacktoberfest-accepted.

**Pull request merged**
